### PR TITLE
Pass FindBugs Analysis

### PR DESCRIPTION
**Pull request by m0jt4b4**
- [x] This commit resolves bugs reported by maven FindBugs plugin

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
This seems to be failing because of the docker-based integration tests.

**Comment by m0jt4b4** [comment]
> This seems to be failing because of the docker-based integration tests.

There is a bug report from FindBugs regarding the unused URI variable in Transport.java
First I decided to remove the variable in commit 219fecea9cd16574a47706c054a4c03388df6b72
which results in docker error for (prepare-etcd-server). Now I put the variale back in the place in commit 2ed44dd37f48b7a5d8542b471919117d602038a2 which resolved the docker issue, but still FindBugs reports it.

Should we ignore this bug?

**Comment by m0jt4b4** [comment]
as I read in the [logs](https://ci.jenkins.io/job/Plugins/job/in-toto-plugin/view/change-requests/job/PR-8/6/consoleFull), the jenkinsfile is read from commit 407a2d155a9bf8058d42bce412fa55115b2f0795 which is part of master! I think we should directly commit in master!

**Comment by SantiagoTorres** [comment]
@m0jt4b4 looks good! thanks!

**Pull request merged**
